import {
	Stack,
	Stat,
	StatArrow,
	StatHelpText,
	StatLabel,
	StatNumber,
} from "@chakra-ui/react";
import Head from "next/head";
import { Card, useAuth } from "@saas-ui/react";

export default function Home() {
	const { user } = useAuth();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Stack direction='column' gap={8} w='full'>
				<Stack direction='row' w='full' gap={4}>
					<Card
						w='full'
						display='flex'
						justifyContent='center'
						alignItems='center'
						p={3}
					>
						<Stat>
							<StatLabel>Sent</StatLabel>
							<StatNumber>345,670</StatNumber>
							<StatHelpText>
								<StatArrow type='increase' />
								23.36%
							</StatHelpText>
						</Stat>
					</Card>
					<Card
						w='full'
						display='flex'
						justifyContent='center'
						alignItems='center'
						p={3}
					>
						<Stat>
							<StatLabel>Clicked</StatLabel>
							<StatNumber>45</StatNumber>
							<StatHelpText>
								<StatArrow type='decrease' />
								9.05%
							</StatHelpText>
						</Stat>
					</Card>
					<Card
						w='full'
						display='flex'
						justifyContent='center'
						alignItems='center'
						p={3}
					>
						<Stat>
							<StatLabel>Clicked</StatLabel>
							<StatNumber>45</StatNumber>
							<StatHelpText>
								<StatArrow type='decrease' />
								9.05%
							</StatHelpText>
						</Stat>
					</Card>
					<Card
						w='full'
						display='flex'
						justifyContent='center'
						alignItems='center'
						p={3}
					>
						<Stat>
							<StatLabel>Sent</StatLabel>
							<StatNumber>345,670</StatNumber>
							<StatHelpText>
								<StatArrow type='increase' />
								23.36%
							</StatHelpText>
						</Stat>
					</Card>
				</Stack>
				<Card w='full' p={3}>
					<pre>
						<code>{JSON.stringify(user, null, 2)}</code>
					</pre>
				</Card>
			</Stack>
		</>
	);
}
